### ISSUE TITLE
Clicking on one cafe entry does not show up details

### ISSUE THREAD

**Issue by COLABORATI** [serversideup/roastandbrew#1]
When I select one cafe entry from the list I see no details, look at this screenshot:
 
![2017-11-18_brew-and-coffee-no-detail-view](https://user-images.githubusercontent.com/6514273/32982131-d92518ea-cc7f-11e7-902a-919c873f606d.png)

The app div just stays empty: 
```
<div id="app">
 <router-view></router-view>
</div>
```

**Comment by danpastori** [comment]
Hi @COLABORATI, 

This should be fixed in the latest push! Let me know if you have any questons!
