### ISSUE TITLE
Cordova application

### ISSUE THREAD

**Issue by Astriel** [serversideup/roastandbrew#13]
Hello again,

Any chance to have an upcoming tutorial on how to transform the WEB application to a Cordova mobile application ? This is taken from your first part of the tutorial : 

> So in this article series, we will start by setting up a web app that allows for a consumable API in the back end and authentication with social providers. We will then move to a mobile app using Cordova and the same components we used. The app will be an SPA on the web side and the mobile side. When the web side is complete there should be very little configuration to transfer the app using the same components, styles, and structure to turn it into a mobile app. Of course there are a few tweaks that should be made, but we should be able to isolate those easily. This will allow for simultaneous development that’s easily transferred between web and mobile.

Thanks in advance !

**Comment by jaydrogers** [comment]
Sorry for the long delay on this, but just letting you know that what you are asking for is coming very soon!

We just launched a brand new version of Roast at https://roastandbrew.coffee

We have everything that you will need in our upcoming book: https://serversideup.net/ultimate-guide-to-building-apis-and-spas-with-laravel-and-vuejs/

We actually just got the app into the Google Play store the other day (hoping Apple will approve ours soon): https://play.google.com/store/apps/details?id=coffee.roastandbrew.mobile

I hope you will find our book as a useful resource!
