### ISSUE TITLE
Website validation is too explicit

### ISSUE THREAD

**Issue by mikemand** [serversideup/roastandbrew#2]
Your [website validation regex](https://github.com/serversideup/roastandbrew/blob/master/resources/assets/js/pages/NewCafe.vue#L335) is very explicit. It **requires** `www.` and disallows a trailing slash.

While not the end of the world, I spent more time than I would like to admit trying to figure out why I couldn't save a new café.

**Comment by danpastori** [comment]
Hi @mikemand ,

I got the regex updated, sorry for the confusion! It should work a lot better now!
