### ISSUE TITLE
Problem in uploading photo

### ISSUE THREAD

**Issue by AhmadOf** [serversideup/roastandbrew#3]
When I tried to edit a cafe to upload a photo It's not working and after some investigation I figured out it's related to PUT method and multipart/form-data so I added:
formData.append('_method', 'PUT')
to putEditCafe in api/cafe.js and changed axios method from put to post so the problem solved in this way.

**Comment by danpastori** [comment]
Awesome thanks for finding that! I made the fix and pushed this into the repo!
