### ISSUE TITLE
Error in one of the getters of Users.js

### ISSUE THREAD

**Issue by geoker** [serversideup/roastandbrew#4]
In the Vuex module Users there is an error in one of the getters.    

modules\users.js

getUserLoadStatus( state ){
      return function(){
        return state.userLoadStatus;
      }
    },

**Comment by geoker** [comment]
this should be : 

> getUserLoadStatus( state ){
> return state.userLoadStatus;
> }, 
> 

not 

> getUserLoadStatus( state ){
> return function(){
> return state.userLoadStatus;
> }
> },


There's another return in the same function that messes things up when we call 
this.$store.getters.getUserLoadStatus;  
      


P.S Thanks for the awesome tutorial

**Comment by danpastori** [comment]
Glad you like the tutorial! So the reason we have this one as a function is in the `/resources/assets/js/routes.js` file, we have a method called `requireAuth()` in this method we watch for the load status to change before proceeding to see if the user is authenticated or not. In JS the only way to watch for something is through a function return. This does mean we have to call getUserLoadStatus every time as a method, but we can watch for when it changes to determine if we can test for authentication or not. Let me know if that makes sense!

**Comment by geoker** [comment]
I did not know that.  thanks for the explanation!

For my project, i followed the tutorial step by step until this lesson, where it encourages the reader to implement his own user model: https://serversideup.net/tutorial-progress/ .

Sorry for wasting your time!

**Comment by danpastori** [comment]
No Problem! Let me know if anything else comes up!
